version: '3'
services:
  chatroom-server:
    container_name: chatroom-server
    build: .
    environment:
      - MONGO_DB=mongodb://mongo:27017/my-db
      - CHATROOM_SECRET=${CHATROOM_SECRET}
      - SERVER_PORT=8083
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8083:8083
  mongo:
    container_name: chatroom-server-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
